// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace tech.project.tests.conventions
{
    using System.Collections.ObjectModel;

    // EmployeeTraining
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class EmployeeTraining
    {
        public System.Guid Id { get; set; } // Id (Primary key)
        public System.Guid EmployeeId { get; set; } // EmployeeId
        public System.Guid TrainingId { get; set; } // TrainingId
        public System.DateTime AttendDate { get; set; } // AttendDate

        // Foreign keys
        public virtual Employee Employee { get; set; } // FK_EmployeeTraining_ToEmployee
        public virtual Training Training { get; set; } // FK_EmployeeTraining_ToTraining

        public EmployeeTraining()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
