// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.51
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

namespace tech.project.tests.conventions
{
    using System.Collections.ObjectModel;

    // EmployeeTraining
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.24.0.0")]
    public partial class EmployeeTrainingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<EmployeeTraining>
    {
        public EmployeeTrainingConfiguration()
            : this("dbo")
        {
        }

        public EmployeeTrainingConfiguration(string schema)
        {
            ToTable("EmployeeTraining", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").IsRequired().HasColumnType("uniqueidentifier").HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.EmployeeId).HasColumnName(@"EmployeeId").IsRequired().HasColumnType("uniqueidentifier");
            Property(x => x.TrainingId).HasColumnName(@"TrainingId").IsRequired().HasColumnType("uniqueidentifier");
            Property(x => x.AttendDate).HasColumnName(@"AttendDate").IsRequired().HasColumnType("datetime");

            // Foreign keys
            HasRequired(a => a.Employee).WithMany(b => b.EmployeeTrainings).HasForeignKey(c => c.EmployeeId).WillCascadeOnDelete(false); // FK_EmployeeTraining_ToEmployee
            HasRequired(a => a.Training).WithMany(b => b.EmployeeTrainings).HasForeignKey(c => c.TrainingId).WillCascadeOnDelete(false); // FK_EmployeeTraining_ToTraining
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
